print('        ===========        ')
print('  Coded By SupianHariies_ID')
print('Judul : Data type Pada Python       ')
print('        ===========        ')
angka1 = input('iInput Type Code INT Ex (10) ? ')
print(angka1)
print(type(angka1))
print('===========')
angka2 = input('Input Type Code Float ex (12.34) ? ')
print(angka2)
print(type(angka2))
print('===========')
angka3 = input('Input Type Code Long Ex (Angka Sebanyaknya) ? ')
print(angka3)
print(type(angka3))
print('===========')
angka4 = input('input Type Code complex Ex (10+1j) ? ')
print(angka4)
print(type(angka4))
print('===========')
daftar_angka = input('Input Type Code List ex ( [1,2,3] ) ? ')
print(daftar_angka)
print(type(daftar_angka))
print('===========')
a = 'Thank Udah Make Ini hnya Sebagai Bahan Belajar saja'
print(a)